### PR TITLE
Map incoming hiera data as dot-separated hierarchy

### LINKED ISSUE #76: Does not seem possible to add AWS tags via lookup data when run as a controller
**Describe the bug**
When running Lyra as a controller it does not seem possible to add AWS tags via lookup data:

> did this:
> ```apiVersion: lyra.example.com/v1alpha1
> kind: Workflow
> metadata:
>   name: dbt-workflow
> spec:
>   workflowName: "dbt"
>   refreshTime: 10
>   data:
>     aws:
>       tags:
>         created_by: lyra
>         department: engineering
>         project: incubator
>         lifetime: 1h
>         Name: dimitri-lyra-test
> ```
> Now the output is:
> ```E0125 12:14:07.962996    1865 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1alpha1.Workflow: v1alpha1.WorkflowList.Items: []v1alpha1.Workflow: v1alpha1.Workflow.Spec: v1alpha1.WorkflowSpec.Data: ReadString: expects " or n, but found {, error found in #10 byte of ...|":{"aws":{"tags":{"N|..., bigger context ...|a-11e9-89fa-42010a840124"},"spec":{"data":{"aws":{"tags":{"Name":"dimitri-lyra-test","created_by":"l|...```
> and this repeats indefinitely

Lyra works as expected when run directly with CLI if the data is hard-wired into the manifest.

**To Reproduce**
Run Lyra in controller mode and create the above Workflow resource.

**Expected behavior**
Lyra runs the workflow the same in both controller and CLI mode.

**Additional context**
Found by Dimitri

### PR DESCRIPTION
**Pull request by markfuller**
Parse out keys like `aws.tags.created_by` to create a deep map, converts to eval.OrderedMap and passes them to hiera

Closes #76

### CODE REVIEW

File: pkg/apply/apply.go [hunk 1]
```diff
@@ -42,12 +44,37 @@ func (a *Applicator) ApplyWorkflowWithHieraData(workflowName string, hieraData m
 
 func (a *Applicator) applyWithHieraData(workflowName string, hieraData map[string]string, intent wfapi.Operation) {
 	tp := func(ic lookup.ProviderContext, key string, _ map[string]eval.Value) (eval.Value, bool) {
-		v, ok := hieraData[key]
-		return types.WrapString(v), ok
+		m := convertToDeepMap(hieraData)
```
Comment (thallgren) [inline pkg/apply/apply.go]: This is very inefficient. Do the conversion on line 46 instead (outside of this func). Otherwise, the conversion takes place once for every lookup.

File: pkg/apply/apply.go [hunk 2]
```diff
@@ -42,12 +44,37 @@ func (a *Applicator) ApplyWorkflowWithHieraData(workflowName string, hieraData m
...
+		hclog.Default().Debug("converted map to hiera data", "m", m)
+		v := eval.Wrap(nil, m).(eval.OrderedMap)
+		return v, true
```
Comment (thallgren) [inline pkg/apply/apply.go]: This will return the whole map. You need `return v.Get4(key)` here.

File: pkg/apply/apply.go (hunk 1 above)
Comment (markfuller) [reply pkg/apply/apply.go]: 👍

File: pkg/apply/apply.go (hunk 2 above)
Comment (markfuller) [reply pkg/apply/apply.go]: Change made.

File: pkg/apply/apply.go (hunk 1 above)
Comment (markfuller) [reply pkg/apply/apply.go]: Change made.
